"""server_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jpRca101vaQtCwT6OPlI0AIDJWEQlZRo
"""
from geodist import GeoDist
import pandas as pd
import re
import pickle
import sklearn
import catboost

SOURCE_FILES_PATH = "sources/"

import warnings

warnings.filterwarnings('ignore')


def dist(x):
    s = [float(s) for s in x]
    s[0], s[1] = s[1], s[0]
    s = tuple(s)
    res = float(format(GeoDist([s]).distance(37.617734, 55.751999) / 1000, '.3f'))
    return res


def ml_price(data):
    data['coords'] = dist(data['coords'])
    data['house_floors'] = 10
    data['floor'] = 5
    data['kitchen_area'] = 9
    data['balcony'] = 'лоджия'
    data = pd.Series(data)
    data = data[['coords', 'rooms_count', 'year', 'house_floors', 'material', 'floor', 'flat_area', 'kitchen_area', \
                 'balcony', 'metro', 'condition']]

    print(data)

    loaded_model = pickle.load(open('C:/Users/didig/PycharmProjects/pythonProject/lct_model.sav', 'rb'))
    pred = loaded_model.predict(data)
    cost = pd.Series(pred)
    cost = cost // 100000 * 100000 + 90000
    cost = cost.astype(int)
    print(cost[0])
    return int(cost[0])
